### PR TITLE
update to ns3 v3.40, Ubuntu 22.04 and Go 1.21.5

### PR DESCRIPTION
**Pull request by larseggert**

### CODE REVIEW

**Comment by marten-seemann** [comment]
Looks like we have two PRs now that do the same thing: #113 and this one. Which one should we take?

**Comment by marten-seemann** [comment]
I fixed CI in #114. Can you rebase please?

**Comment by larseggert** [comment]
@marten-seemann done

**Comment by marten-seemann** [comment]
@larseggert Thank you!
Do you have any thoughts regarding this PR vs #113?

**Comment by jaikiran** [comment]
Hello Lars, Marten, please go ahead with this current PR. I see that this one also upgrades ubuntu and Go version to a higher version than what my PR does. 

As for the changes to the ns3 build itself,  in my PR, I introduced a complete new build file (`CMakeLists.txt`) to build the quic interop scenarios and that build file would be part of this repo. I see that Lars patches the ns3 build system files to build the quic interop scenarios (which is what was anyway being done so far). I don't have any specific preference and since the changes in this current PR appear to be functional, I think it's better to go ahead with this current PR.

I do plan to apply the changes in this PR locally and build the simulator container and run the quic interop tests. I will get to it in a few days, but integrating this PR doesn't have to wait for it - I can open a new issue/PR if I run into any issues with this change. Thank you for these upgrades.

**Comment by marten-seemann** [comment]
Thank you @jaikiran and @larseggert!

**Review by marten-seemann — APPROVED** [review]

**Pull request merged**
